name: Pipeline

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: yarn

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint
      # - name: Configure NPM for Publish
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      # - name: Publish
      #   run: |
      #     npm --no-git-tag-version version prerelease --preid=commit.$(git rev-parse --short HEAD)
      #     npm publish --tag commit
